### ISSUE TITLE
ERC20 generated code fails to compile with forc 0.60.0

### ISSUE THREAD

**Issue by sdankel** [ourovoros-io/charcoal#2]
For this example: https://gist.github.com/fuel-service-user/09232d1485c507658ba47abca263fd6c#file-playground-sol

The error is:

```
  --> /Users/sophiedankel/Development/sway-playground/projects/swaypad/src/main.sw:20:5
   |
18 | 
19 | impl AbiEncode for ERC20Event {
20 |     fn abi_encode(self, buffer: Buffer) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected: Buffer 
found:    () 
help:     The definition of this function must match the one in the trait "AbiEncode" declaration.
21 |         match self {
22 |             ERC20Event::Approval((a, b, c)) => {
   |
____

  Aborting due to 1 error.
```

The issue is that the generated code for abi_encode does not return a value:

This [line](https://gist.github.com/fuel-service-user/09232d1485c507658ba47abca263fd6c#file-playground-sw-L20) should be ` fn abi_encode(self, buffer: core::codec::Buffer) -> core::codec::Buffer {`

**Comment by camden-smallwood** [comment]
This has been resolved in commit [7c2fd7d](https://github.com/ourovoros-io/charcoal/commit/7c2fd7d1539d15304616269f11dbe20c1bd5d6ca).
