### ISSUE TITLE
translate under hardhat framework

### ISSUE THREAD

**Issue by zxzyy10** [ourovoros-io/charcoal#6]
I am trying to use the tool to translate UniswapV3 code, and I have encountered the following two issues:

1 In Hardhat, when importing files from node_modules, the paths are not recognized. I need to change them to relative paths for them to be recognized. For example:

```solidity
import '@openzeppelin/contracts/math/SafeMath.sol';
``` 
needs to be changed to:
```solidity
import '../node_modules/@openzeppelin/contracts/math/SafeMath.sol';
``` 

2 Some structures cannot be recognized, causing the program to panic and terminate execution.

![1732075543389](https://github.com/user-attachments/assets/f7e4574f-945f-4036-958f-159cf35d31a8)

My suggestion is to consider using UniswapV3 as a test case, since many applications rely on the concentrated liquidity AMM mechanism proposed by UniswapV3 for price discovery and liquidity management. If the tool can effectively translate the main contracts of UniswapV3 (with any unimplemented parts marked with TODO), it would make Charcoal an excellent tool for developers to improve efficiency.

**Comment by camden-smallwood** [comment]
Thanks for pointing these out, we will add UniswapV3 to our test coverage and will attempt to get these resolved as soon as possible.

**Comment by zxzyy10** [comment]
> Thanks for pointing these out, we will add UniswapV3 to our test coverage and will attempt to get these resolved as soon as possible.

I tried new version today,and still face some issue 

I'm not sure if this latest version supports the Uniswap V3 series of contracts, or if it's still in the testing phase.

![image](https://github.com/user-attachments/assets/49b1b553-b6ed-43c9-b385-44d713052504)

**Comment by GeorgiosDelkos** [comment]
Hi there @zxzyy10 as @camden-smallwood pointed out we are actively working on fixing those issues and have the uniswap v2-3-4 translating. We are going to update the issue as soon as we fix everything for uniswap. Thank you

**Comment by GeorgiosDelkos** [comment]
Hi there @zxzyy10  I am closing this one as you can run [test_coverage.rs](https://github.com/ourovoros-io/charcoal/blob/main/tests/test_coverage.rs) test [test_uniswap_v3_core](https://github.com/ourovoros-io/charcoal/blob/e69a6ffaf3e7eaf9f3ceea543087ea59ec5fd5d1/tests/test_coverage.rs#L57) and test [test_uniswap_v3_periphery](https://github.com/ourovoros-io/charcoal/blob/e69a6ffaf3e7eaf9f3ceea543087ea59ec5fd5d1/tests/test_coverage.rs#L64C4-L64C29) and check the progress there. Please note that some parts of the uniswap codebase are not going to be translated to sway automatically and there is need there for some manual work. Feel free to also jump into Fuel Builders channel in Telegram for more information.
